RRQ_MODE = 1
WRQ_MODE = 2
DATA_MODE = 3
ACK_MODE = 4
ERROR_MODE = 5
MAX_BYTES = 512
MAX_BUFFER_WRQ = 508

# Error codes
ERR_NOT_DEFINED = 0
ERR_FILE_NOT_FOUND = 1
ERR_ACCESS_VIOLATION = 2
ERR_DISK_FULL = 3
ERR_ILLEGAL_TFTP_OP = 4
ERR_UNKNOWN_TID = 5
ERR_FILE_ALREADY_EXISTS = 6  # not implemented, just overwrite existing file
ERR_NO_SUCH_USER = 7
